### PR TITLE
Draft: support faster inference methods

### PR DESCRIPTION
**Pull request by pszemraj**
support faster and advanced inference methods

- `torch.compile`
- optimum onnx
- use fire for the CLI

### CODE REVIEW

**Comment by pszemraj** [comment]
after further thought I am going to update the UI/app in a later round of improvements bc I don't have time for it these days

**Review by pszemraj — COMMENTED** [review]
changes look fine from me self-reviewing what I did.. will clone into a colab and test basics to make sure

**Comment by lefnire** [comment]
This would be awesome! Does it handle the conversion of a huggingface model to optimized onnx pretty automatically? Or do you need to convert manually first, and it supports loading in an onnx model?

**Comment by pszemraj** [comment]
#9 will now be handled by this

**Comment by pszemraj** [comment]
oook finally happy with it

**Pull request merged**
